
main:
	g++ -g3 -Wall -std=c++17 -o main main.cpp			\
	../network/socket.cpp ../network/requests.cpp		\
	../message.cpp ../storage/database.cpp				\
	../router/namespace.cpp ../router/neighbors.cpp		\
	../storage/nodes.cpp ../storage/clients.cpp			\
	../encryption.cpp ../storage/tasks.cpp				\
	../router/garlic.cpp ../storage/neighbors.cpp		\
	../storage/routes.cpp ../router/find.cpp			\
	../router/nodes.cpp ../storage/garlic.cpp			\
	-pthread -lsqlite3 -lsodium