version: "2"

services:
    network_1:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/src
        expose:
            - 1122
        ports:
            - 1122:1122
        command: "./spruce"
        networks:
            - bridge
    network_2:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/src
        expose:
            - 1123
        ports:
            - 1123:1123
        networks:
            - bridge
        command: "./spruce"
    network_3:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/src
        expose:
            - 1124
        ports:
            - 1124:1124
        networks:
            - bridge
        command: "./spruce"
    network_4:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/src
        expose:
            - 1155
        ports:
            - 1155:1155
        networks:
            - bridge
        command: "./spruce"
    test_find:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/src
        networks:
            - bridge
        command: "php -f find.php"
    test_status:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/src
        networks:
            - bridge
        command: "php -f status.php"

networks:
    bridge:
        driver: bridge
        ipam:
            config:
                - subnet: 172.10.0.0/16
                  gateway: 172.10.5.254
                  aux_addresses:
                      network_1: 172.10.1.2
                      network_2: 172.10.1.3
                      network_3: 172.10.1.4
                      network_4: 172.10.1.5
                      test_find: 172.10.1.6
                      test_status: 172.10.1.7
